### ISSUE TITLE
[12.0] resource_booking

### ISSUE THREAD

**Issue by matteoopenf** [OCA/calendar#67]
## Module
resource_booking

## Describe the bug
Try to install the module on odoo.sh and obtain 
Failed to load registry
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 179, in load_module_graph
    load_openerp_module(package.name)
  File "/home/odoo/src/odoo/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/home/odoo/src/odoo/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 2, in <module>
  File "/home/odoo/src/user/b_OCA/calendar/resource_booking/controllers/__init__.py", line 1, in <module>
    from . import portal
  File "/home/odoo/src/user/b_OCA/calendar/resource_booking/controllers/portal.py", line 7, in <module>
    from dateutil.parser import isoparse
ImportError: cannot import name 'isoparse'

## To Reproduce
**Affected versions**:

- [ ] 12.0

1. create an env 12.0 on odoo.sh
2. add repo OCA  Calendard
3. obtain error:
4. Failed to load registry
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 179, in load_module_graph
    load_openerp_module(package.name)
  File "/home/odoo/src/odoo/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/home/odoo/src/odoo/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 2, in <module>
  File "/home/odoo/src/user/b_OCA/calendar/resource_booking/controllers/__init__.py", line 1, in <module>
    from . import portal
  File "/home/odoo/src/user/b_OCA/calendar/resource_booking/controllers/portal.py", line 7, in <module>
    from dateutil.parser import isoparse
ImportError: cannot import name 'isoparse'

**Expected behavior**
not obtain error

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by pedrobaeza** [comment]
Update your dateutil library version: https://github.com/datopian/metastore-lib/issues/2
