### ISSUE TITLE
create type resource_booking error

### ISSUE THREAD

**Issue by jorgehdo81** [OCA/calendar#99]
## Module
resource_booking

## Describe the bug

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Program Files\server\odoo\http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files\server\odoo\http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files\server\odoo\http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files\server\odoo\http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files\server\odoo\http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files\server\odoo\addons\web\controllers\main.py", line 1326, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Program Files\server\odoo\addons\web\controllers\main.py", line 1318, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files\server\odoo\api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files\server\odoo\api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\Program Files\server\odoo\models.py", line 6367, in onchange
    defaults = self.default_get(missing_names)
  File "C:\Program Files\server\odoo\models.py", line 1410, in default_get
    defaults[name] = field.default(self)
  File "C:\Program Files\server\odoo\addons\resource_booking\models\resource_booking_type.py", line 87, in <lambda>
    default=lambda self: self._default_resource_calendar(),
  File "C:\Program Files\server\odoo\addons\resource_booking\models\resource_booking_type.py", line 104, in _default_resource_calendar
    return self._default_company().resource_calendar_id
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\server\odoo\http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files\server\odoo\http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'resource.booking.type' object has no attribute '_default_company'

## To Reproduce
**Affected versions**:

odoo 15

**Comment by pedrobaeza** [comment]
You are not using latest source code version that contains this patch: 406f3fbd42d75e5e9b85d7edf6626572561d35ed
